class Icon:
    def __init__(self, theme):
        self.fi_rr_add = None
        self.fi_rr_alarm_clock = None
        self.fi_rr_align_center = None
        self.fi_rr_align_justify = None
        self.fi_rr_align_left = None
        self.fi_rr_align_right = None
        self.fi_rr_ambulance = None
        self.fi_rr_angle_double_left = None
        self.fi_rr_angle_double_right = None
        self.fi_rr_angle_double_small_left = None
        self.fi_rr_angle_double_small_right = None
        self.fi_rr_angle_down = None
        self.fi_rr_angle_left = None
        self.fi_rr_angle_right = None
        self.fi_rr_angle_small_down = None
        self.fi_rr_angle_small_left = None
        self.fi_rr_angle_small_right = None
        self.fi_rr_angle_small_up = None
        self.fi_rr_angle_up = None
        self.fi_rr_apps_add = None
        self.fi_rr_apps_delete = None
        self.fi_rr_apps_sort = None
        self.fi_rr_apps = None
        self.fi_rr_archive = None
        self.fi_rr_arrow_down = None
        self.fi_rr_arrow_left = None
        self.fi_rr_arrow_right = None
        self.fi_rr_arrow_small_down = None
        self.fi_rr_arrow_small_left = None
        self.fi_rr_arrow_small_right = None
        self.fi_rr_arrow_small_up = None
        self.fi_rr_arrow_up = None
        self.fi_rr_asterisk = None
        self.fi_rr_backpack = None
        self.fi_rr_badge = None
        self.fi_rr_ban = None
        self.fi_rr_band_aid = None
        self.fi_rr_bank = None
        self.fi_rr_barber_shop = None
        self.fi_rr_baseball = None
        self.fi_rr_basketball = None
        self.fi_rr_bell_ring = None
        self.fi_rr_bell_school = None
        self.fi_rr_bell = None
        self.fi_rr_billiard = None
        self.fi_rr_bold = None
        self.fi_rr_book_alt = None
        self.fi_rr_book = None
        self.fi_rr_bookmark = None
        self.fi_rr_bowling = None
        self.fi_rr_box_alt = None
        self.fi_rr_box = None
        self.fi_rr_briefcase = None
        self.fi_rr_broom = None
        self.fi_rr_browser = None
        self.fi_rr_brush = None
        self.fi_rr_bug = None
        self.fi_rr_building = None
        self.fi_rr_bulb = None
        self.fi_rr_calculator = None
        self.fi_rr_calendar = None
        self.fi_rr_camera = None
        self.fi_rr_caret_down = None
        self.fi_rr_caret_left = None
        self.fi_rr_caret_right = None
        self.fi_rr_caret_up = None
        self.fi_rr_check = None
        self.fi_rr_checkbox = None
        self.fi_rr_chess = None
        self.fi_rr_circle_small = None
        self.fi_rr_circle = None
        self.fi_rr_clip = None
        self.fi_rr_clock = None
        self.fi_rr_cloud_check = None
        self.fi_rr_cloud_disabled = None
        self.fi_rr_cloud_download = None
        self.fi_rr_cloud_share = None
        self.fi_rr_cloud_upload = None
        self.fi_rr_cloud = None
        self.fi_rr_comment_alt = None
        self.fi_rr_comment = None
        self.fi_rr_compress_alt = None
        self.fi_rr_compress = None
        self.fi_rr_computer = None
        self.fi_rr_cookie = None
        self.fi_rr_copy_alt = None
        self.fi_rr_copy = None
        self.fi_rr_copyright = None
        self.fi_rr_cream = None
        self.fi_rr_credit_card = None
        self.fi_rr_cross_circle = None
        self.fi_rr_cross_small = None
        self.fi_rr_cross = None
        self.fi_rr_crown = None
        self.fi_rr_cursor_finger = None
        self.fi_rr_cursor_plus = None
        self.fi_rr_cursor_text_alt = None
        self.fi_rr_cursor_text = None
        self.fi_rr_cursor = None
        self.fi_rr_dart = None
        self.fi_rr_dashboard = None
        self.fi_rr_data_transfer = None
        self.fi_rr_database = None
        self.fi_rr_delete = None
        self.fi_rr_diamond = None
        self.fi_rr_dice = None
        self.fi_rr_diploma = None
        self.fi_rr_disk = None
        self.fi_rr_doctor = None
        self.fi_rr_document_signed = None
        self.fi_rr_document = None
        self.fi_rr_dollar = None
        self.fi_rr_download = None
        self.fi_rr_duplicate = None
        self.fi_rr_e_learning = None
        self.fi_rr_earnings = None
        self.fi_rr_edit_alt = None
        self.fi_rr_edit = None
        self.fi_rr_envelope = None
        self.fi_rr_euro = None
        self.fi_rr_exclamation = None
        self.fi_rr_expand = None
        self.fi_rr_eye_crossed = None
        self.fi_rr_eye_dropper = None
        self.fi_rr_eye = None
        self.fi_rr_feather = None
        self.fi_rr_file_add = None
        self.fi_rr_file_ai = None
        self.fi_rr_file_check = None
        self.fi_rr_file_delete = None
        self.fi_rr_file_eps = None
        self.fi_rr_file_gif = None
        self.fi_rr_file_music = None
        self.fi_rr_file_psd = None
        self.fi_rr_file = None
        self.fi_rr_fill = None
        self.fi_rr_film = None
        self.fi_rr_filter = None
        self.fi_rr_fingerprint = None
        self.fi_rr_flag = None
        self.fi_rr_flame = None
        self.fi_rr_flip_horizontal = None
        self.fi_rr_folder_add = None
        self.fi_rr_folder = None
        self.fi_rr_following = None
        self.fi_rr_football = None
        self.fi_rr_form = None
        self.fi_rr_forward = None
        self.fi_rr_ftp = None
        self.fi_rr_gallery = None
        self.fi_rr_glasses = None
        self.fi_rr_globe_alt = None
        self.fi_rr_globe = None
        self.fi_rr_golf = None
        self.fi_rr_graduation_cap = None
        self.fi_rr_graphic_tablet = None
        self.fi_rr_grid_alt = None
        self.fi_rr_grid = None
        self.fi_rr_gym = None
        self.fi_rr_headphones = None
        self.fi_rr_headset = None
        self.fi_rr_heart = None
        self.fi_rr_home = None
        self.fi_rr_hourglass_end = None
        self.fi_rr_hourglass = None
        self.fi_rr_ice_skate = None
        self.fi_rr_id_badge = None
        self.fi_rr_inbox = None
        self.fi_rr_incognito = None
        self.fi_rr_indent = None
        self.fi_rr_infinity = None
        self.fi_rr_info = None
        self.fi_rr_interactive = None
        self.fi_rr_interlining = None
        self.fi_rr_interrogation = None
        self.fi_rr_italic = None
        self.fi_rr_jpg = None
        self.fi_rr_key = None
        self.fi_rr_keyboard = None
        self.fi_rr_label = None
        self.fi_rr_laptop = None
        self.fi_rr_lasso = None
        self.fi_rr_layers = None
        self.fi_rr_layout_fluid = None
        self.fi_rr_letter_case = None
        self.fi_rr_life_ring = None
        self.fi_rr_line_width = None
        self.fi_rr_link = None
        self.fi_rr_lipstick = None
        self.fi_rr_list_check = None
        self.fi_rr_list = None
        self.fi_rr_location_alt = None
        self.fi_rr_lock_alt = None
        self.fi_rr_lock = None
        self.fi_rr_magic_wand = None
        self.fi_rr_makeup_brush = None
        self.fi_rr_marker_time = None
        self.fi_rr_marker = None
        self.fi_rr_medicine = None
        self.fi_rr_megaphone = None
        self.fi_rr_menu_burger = None
        self.fi_rr_menu_dots_vertical = None
        self.fi_rr_menu_dots = None
        self.fi_rr_microphone = None
        self.fi_rr_minus_small = None
        self.fi_rr_minus = None
        self.fi_rr_mobile = None
        self.fi_rr_mode_landscape = None
        self.fi_rr_mode_portrait = None
        self.fi_rr_money = None
        self.fi_rr_mouse = None
        self.fi_rr_music_alt = None
        self.fi_rr_music = None
        self.fi_rr_network_cloud = None
        self.fi_rr_network = None
        self.fi_rr_notebook = None
        self.fi_rr_opacity = None
        self.fi_rr_package = None
        self.fi_rr_paint_brush = None
        self.fi_rr_palette = None
        self.fi_rr_paper_plane = None
        self.fi_rr_password = None
        self.fi_rr_pause = None
        self.fi_rr_pencil = None
        self.fi_rr_pharmacy = None
        self.fi_rr_physics = None
        self.fi_rr_picture = None
        self.fi_rr_ping_pong = None
        self.fi_rr_play_alt = None
        self.fi_rr_play = None
        self.fi_rr_playing_cards = None
        self.fi_rr_plus_small = None
        self.fi_rr_plus = None
        self.fi_rr_poker_chip = None
        self.fi_rr_portrait = None
        self.fi_rr_pound = None
        self.fi_rr_power = None
        self.fi_rr_presentation = None
        self.fi_rr_print = None
        self.fi_rr_protractor = None
        self.fi_rr_pulse = None
        self.fi_rr_quote_right = None
        self.fi_rr_rec = None
        self.fi_rr_receipt = None
        self.fi_rr_rectangle_horizontal = None
        self.fi_rr_rectangle_panoramic = None
        self.fi_rr_rectangle_vertical = None
        self.fi_rr_redo = None
        self.fi_rr_reflect = None
        self.fi_rr_refresh = None
        self.fi_rr_resize = None
        self.fi_rr_resources = None
        self.fi_rr_rewind = None
        self.fi_rr_rocket = None
        self.fi_rr_rotate_right = None
        self.fi_rr_rugby = None
        self.fi_rr_scale = None
        self.fi_rr_school_bus = None
        self.fi_rr_school = None
        self.fi_rr_scissors = None
        self.fi_rr_screen = None
        self.fi_rr_search_alt = None
        self.fi_rr_search = None
        self.fi_rr_settings_sliders = None
        self.fi_rr_settings = None
        self.fi_rr_share = None
        self.fi_rr_shield_check = None
        self.fi_rr_shield_exclamation = None
        self.fi_rr_shield_interrogation = None
        self.fi_rr_shield_plus = None
        self.fi_rr_shield = None
        self.fi_rr_shop = None
        self.fi_rr_shopping_bag_add = None
        self.fi_rr_shopping_bag = None
        self.fi_rr_shopping_cart_add = None
        self.fi_rr_shopping_cart_check = None
        self.fi_rr_shopping_cart = None
        self.fi_rr_shuffle = None
        self.fi_rr_sign_in = None
        self.fi_rr_sign_out = None
        self.fi_rr_signal_alt_1 = None
        self.fi_rr_signal_alt_2 = None
        self.fi_rr_signal_alt = None
        self.fi_rr_skateboard = None
        self.fi_rr_smartphone = None
        self.fi_rr_soap = None
        self.fi_rr_spa = None
        self.fi_rr_speaker = None
        self.fi_rr_spinner_alt = None
        self.fi_rr_spinner = None
        self.fi_rr_square_root = None
        self.fi_rr_square = None
        self.fi_rr_star = None
        self.fi_rr_stats = None
        self.fi_rr_stethoscope = None
        self.fi_rr_sticker = None
        self.fi_rr_stop = None
        self.fi_rr_stopwatch = None
        self.fi_rr_subtitles = None
        self.fi_rr_surfing = None
        self.fi_rr_sword = None
        self.fi_rr_syringe = None
        self.fi_rr_tablet = None
        self.fi_rr_target = None
        self.fi_rr_tennis = None
        self.fi_rr_test_tube = None
        self.fi_rr_test = None
        self.fi_rr_text_check = None
        self.fi_rr_text = None
        self.fi_rr_thumbs_down = None
        self.fi_rr_thumbs_up = None
        self.fi_rr_ticket = None
        self.fi_rr_time_add = None
        self.fi_rr_time_check = None
        self.fi_rr_time_delete = None
        self.fi_rr_time_fast = None
        self.fi_rr_time_forward_sixty = None
        self.fi_rr_time_forward_ten = None
        self.fi_rr_time_forward = None
        self.fi_rr_time_half_past = None
        self.fi_rr_time_oclock = None
        self.fi_rr_time_past = None
        self.fi_rr_time_quarter_past = None
        self.fi_rr_time_quarter_to = None
        self.fi_rr_time_twenty_four = None
        self.fi_rr_tool_crop = None
        self.fi_rr_tool_marquee = None
        self.fi_rr_tooth = None
        self.fi_rr_transform = None
        self.fi_rr_trash = None
        self.fi_rr_treatment = None
        self.fi_rr_trophy = None
        self.fi_rr_umbrella = None
        self.fi_rr_underline = None
        self.fi_rr_undo = None
        self.fi_rr_unlock = None
        self.fi_rr_upload = None
        self.fi_rr_usb_drive = None
        self.fi_rr_user_add = None
        self.fi_rr_user_delete = None
        self.fi_rr_user_remove = None
        self.fi_rr_user_time = None
        self.fi_rr_user = None
        self.fi_rr_users = None
        self.fi_rr_vector_alt = None
        self.fi_rr_vector = None
        self.fi_rr_video_camera = None
        self.fi_rr_volleyball = None
        self.fi_rr_volume = None
        self.fi_rr_wifi_alt = None
        self.fi_rr_world = None
        self.fi_rr_yen = None
        self.fi_rr_zoom_in = None
        self.fi_rr_zoom_out = None

        if theme.dark_mode:
            self.icon_folder = "assets/icons/white"
        else:
            self.icon_folder = "assets/icons/black"

    def load_icons(self):
        self.fi_rr_add = self.icon_folder + "/fi-rr-add.svg"
        self.fi_rr_alarm_clock = self.icon_folder + "/fi-rr-alarm-clock.svg"
        self.fi_rr_align_center = self.icon_folder + "/fi-rr-align_center.svg"
        self.fi_rr_align_justify = self.icon_folder + "/fi-rr-align_justify.svg"
        self.fi_rr_align_left = self.icon_folder + "/fi-rr-align_left.svg"
        self.fi_rr_align_right = self.icon_folder + "/fi-rr-align_right.svg"
        self.fi_rr_ambulance = self.icon_folder + "/fi-rr-ambulance.svg"
        self.fi_rr_angle_double_left = self.icon_folder + "/fi-rr-angle_double_left.svg"
        self.fi_rr_angle_double_right = self.icon_folder + "/fi-rr-angle_double_right.svg"
        self.fi_rr_angle_double_small_left = self.icon_folder + "/fi-rr-angle_double_small_left.svg"
        self.fi_rr_angle_double_small_right = self.icon_folder + "/fi-rr-angle_double_small_right.svg"
        self.fi_rr_angle_down = self.icon_folder + "/fi-rr-angle_down.svg"
        self.fi_rr_angle_left = self.icon_folder + "/fi-rr-angle_left.svg"
        self.fi_rr_angle_right = self.icon_folder + "/fi-rr-angle_right.svg"
        self.fi_rr_angle_small_down = self.icon_folder + "/fi-rr-angle_small_down.svg"
        self.fi_rr_angle_small_left = self.icon_folder + "/fi-rr-angle_small_left.svg"
        self.fi_rr_angle_small_right = self.icon_folder + "/fi-rr-angle_small_right.svg"
        self.fi_rr_angle_small_up = self.icon_folder + "/fi-rr-angle_small_up.svg"
        self.fi_rr_angle_up = self.icon_folder + "/fi-rr-angle_up.svg"
        self.fi_rr_apps_add = self.icon_folder + "/fi-rr-apps_add.svg"
        self.fi_rr_apps_delete = self.icon_folder + "/fi-rr-apps_delete.svg"
        self.fi_rr_apps_sort = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_apps = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_archive = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_down = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_left = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_right = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_small_down = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_small_left = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_small_right = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_small_up = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_arrow_up = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_asterisk = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_backpack = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_badge = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_ban = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_band_aid = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bank = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_barber_shop = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_baseball = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_basketball = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bell_ring = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bell_school = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bell = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_billiard = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bold = self.icon_folder + "/fi-rr-bold.svg"
        self.fi_rr_book_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_book = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bookmark = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bowling = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_box_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_box = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_briefcase = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_broom = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_browser = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_brush = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bug = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_building = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_bulb = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_calculator = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_calendar = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_camera = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_caret_down = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_caret_left = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_caret_right = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_caret_up = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_checkbox = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_chess = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_circle_small = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_circle = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_clip = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_clock = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cloud_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cloud_disabled = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cloud_download = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cloud_share = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cloud_upload = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cloud = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_comment_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_comment = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_compress_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_compress = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_computer = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cookie = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_copy_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_copy = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_copyright = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cream = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_credit_card = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cross_circle = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cross_small = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cross = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_crown = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cursor_finger = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cursor_plus = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cursor_text_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cursor_text = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_cursor = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_dart = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_dashboard = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_data_transfer = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_database = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_delete = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_diamond = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_dice = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_diploma = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_disk = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_doctor = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_document_signed = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_document = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_dollar = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_download = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_duplicate = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_e_learning = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_earnings = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_edit_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_edit = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_envelope = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_euro = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_exclamation = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_expand = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_eye_crossed = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_eye_dropper = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_eye = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_feather = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_add = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_ai = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_delete = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_eps = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_gif = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_music = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file_psd = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_file = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_fill = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_film = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_filter = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_fingerprint = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_flag = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_flame = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_flip_horizontal = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_folder_add = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_folder = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_following = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_football = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_form = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_forward = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_ftp = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_gallery = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_glasses = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_globe_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_globe = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_golf = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_graduation_cap = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_graphic_tablet = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_grid_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_grid = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_gym = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_headphones = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_headset = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_heart = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_home = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_hourglass_end = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_hourglass = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_ice_skate = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_id_badge = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_inbox = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_incognito = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_indent = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_infinity = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_info = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_interactive = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_interlining = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_interrogation = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_italic = self.icon_folder + "/fi-rr-italic.svg"
        self.fi_rr_jpg = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_key = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_keyboard = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_label = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_laptop = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_lasso = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_layers = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_layout_fluid = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_letter_case = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_life_ring = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_line_width = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_link = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_lipstick = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_list_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_list = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_location_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_lock_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_lock = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_magic_wand = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_makeup_brush = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_marker_time = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_marker = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_medicine = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_megaphone = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_menu_burger = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_menu_dots_vertical = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_menu_dots = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_microphone = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_minus_small = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_minus = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_mobile = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_mode_landscape = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_mode_portrait = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_money = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_mouse = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_music_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_music = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_network_cloud = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_network = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_notebook = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_opacity = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_package = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_paint_brush = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_palette = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_paper_plane = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_password = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_pause = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_pencil = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_pharmacy = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_physics = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_picture = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_ping_pong = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_play_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_play = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_playing_cards = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_plus_small = self.icon_folder + "/fi-rr-plus-small.svg"
        self.fi_rr_plus = self.icon_folder + "/fi-rr-plus.svg"
        self.fi_rr_poker_chip = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_portrait = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_pound = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_power = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_presentation = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_print = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_protractor = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_pulse = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_quote_right = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rec = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_receipt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rectangle_horizontal = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rectangle_panoramic = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rectangle_vertical = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_redo = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_reflect = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_refresh = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_resize = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_resources = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rewind = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rocket = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rotate_right = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_rugby = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_scale = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_school_bus = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_school = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_scissors = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_screen = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_search_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_search = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_settings_sliders = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_settings = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_share = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shield_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shield_exclamation = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shield_interrogation = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shield_plus = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shield = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shop = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shopping_bag_add = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shopping_bag = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shopping_cart_add = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shopping_cart_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shopping_cart = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_shuffle = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_sign_in = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_sign_out = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_signal_alt_1 = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_signal_alt_2 = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_signal_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_skateboard = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_smartphone = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_soap = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_spa = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_speaker = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_spinner_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_spinner = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_square_root = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_square = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_star = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_stats = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_stethoscope = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_sticker = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_stop = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_stopwatch = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_subtitles = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_surfing = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_sword = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_syringe = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_tablet = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_target = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_tennis = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_test_tube = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_test = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_text_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_text = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_thumbs_down = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_thumbs_up = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_ticket = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_add = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_check = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_delete = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_fast = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_forward_sixty = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_forward_ten = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_forward = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_half_past = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_oclock = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_past = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_quarter_past = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_quarter_to = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_time_twenty_four = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_tool_crop = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_tool_marquee = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_tooth = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_transform = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_trash = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_treatment = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_trophy = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_umbrella = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_underline = self.icon_folder + "/fi-rr-underline.svg"
        self.fi_rr_undo = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_unlock = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_upload = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_usb_drive = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_user_add = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_user_delete = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_user_remove = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_user_time = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_user = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_users = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_vector_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_vector = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_video_camera = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_volleyball = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_volume = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_wifi_alt = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_world = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_yen = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_zoom_in = self.icon_folder + "/fi-rr-REPLACE.svg"
        self.fi_rr_zoom_out = self.icon_folder + "/fi-rr-REPLACE.svg"